/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientehan;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author berto
 */
public class ClienteHan extends javax.swing.JFrame {

    /**
     * Creates new form ClienteHan
     */
    public ClienteHan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verificarsaldo = new javax.swing.JButton();
        nomeusuario = new javax.swing.JTextField();
        senhausuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valordeposito = new javax.swing.JTextField();
        nomeusuario1 = new javax.swing.JTextField();
        enviardeposito = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        valorsaque = new javax.swing.JTextField();
        nomeusuario2 = new javax.swing.JTextField();
        enviarsaque = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nomeusuario3 = new javax.swing.JTextField();
        senhausuario1 = new javax.swing.JTextField();
        enviarCadastro = new javax.swing.JButton();
        saldousuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeusuarioantigo = new javax.swing.JTextField();
        nomeusuarionovo = new javax.swing.JTextField();
        senhausuarioantigo = new javax.swing.JTextField();
        senhausuarionovo = new javax.swing.JTextField();
        enviarAlteracao = new javax.swing.JButton();
        nomeusuario4 = new javax.swing.JTextField();
        senhausuario2 = new javax.swing.JTextField();
        consultarUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        verificarsaldo.setText("Verificar");
        verificarsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarsaldoActionPerformed(evt);
            }
        });

        nomeusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeusuarioActionPerformed(evt);
            }
        });

        senhausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhausuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo");

        jLabel2.setText("Deposito");

        nomeusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeusuario1ActionPerformed(evt);
            }
        });

        enviardeposito.setText("Enviar");
        enviardeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviardepositoActionPerformed(evt);
            }
        });

        jLabel3.setText("Saque");

        enviarsaque.setText("Enviar");
        enviarsaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarsaqueActionPerformed(evt);
            }
        });

        jLabel4.setText("Cadastrar Novo Usuário");

        enviarCadastro.setText("Enviar");
        enviarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCadastroActionPerformed(evt);
            }
        });

        jLabel5.setText("Alterar Cadastro");

        nomeusuarioantigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeusuarioantigoActionPerformed(evt);
            }
        });

        enviarAlteracao.setText("Enviar");
        enviarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAlteracaoActionPerformed(evt);
            }
        });

        consultarUsuario.setText("Consultar");
        consultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setText("Consultar Usuario");

        jLabel7.setText("Nome");

        jLabel8.setText("Senha");

        jLabel9.setText("Valor");

        jLabel10.setText("Conta");

        jLabel11.setText("Valor");

        jLabel12.setText("Conta");

        jLabel13.setText("Nome");

        jLabel14.setText("Senha");

        jLabel15.setText("Saldo");

        jLabel16.setText("Nome Atual");

        jLabel17.setText("Novo Nome");

        jLabel18.setText("Senha Atual");

        jLabel19.setText("Nova Senha");

        jLabel20.setText("Nome");

        jLabel21.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(nomeusuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(valordeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addComponent(enviarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(nomeusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enviardeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(nomeusuarioantigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valorsaque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(nomeusuarionovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enviarsaque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhausuarioantigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(129, 129, 129)
                        .addComponent(senhausuarionovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel20)
                        .addGap(182, 182, 182)
                        .addComponent(enviarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(nomeusuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(senhausuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(consultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(senhausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verificarsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(senhausuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(saldousuario))))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(nomeusuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(senhausuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(verificarsaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(senhausuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addComponent(saldousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(valordeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(enviarCadastro)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(nomeusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(enviardeposito)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(nomeusuarioantigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11))
                    .addComponent(jLabel17))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorsaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeusuarionovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel18)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(enviarsaque))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(senhausuarioantigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel19)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(senhausuarionovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20))
                    .addComponent(enviarAlteracao))
                .addGap(6, 6, 6)
                .addComponent(nomeusuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(senhausuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(consultarUsuario))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeusuarioActionPerformed

    }//GEN-LAST:event_nomeusuarioActionPerformed

    private void senhausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhausuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhausuarioActionPerformed

    private void verificarsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarsaldoActionPerformed
        double teste = 0;
        teste = saldoUser(this.nomeusuario.getText(), this.senhausuario.getText());
        if(teste == 0.0){
            JOptionPane.showMessageDialog(null, "Conta não cadastrada ou senha incorreta");
        }else{
            JOptionPane.showMessageDialog(null, "Saldo: R$ " + teste);
        }
    }//GEN-LAST:event_verificarsaldoActionPerformed

    private void enviardepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviardepositoActionPerformed
            boolean teste = false;
            double valorDeposito = Double.parseDouble(this.valordeposito.getText());
            teste = deposito(valorDeposito, this.nomeusuario1.getText());
            if(teste == true){
            JOptionPane.showMessageDialog(null, "Valor insuficiente ou Conta não cadastrada");   
            }
            else{
            JOptionPane.showMessageDialog(null, "Deposito realizado com sucesso");        
                    }
    }//GEN-LAST:event_enviardepositoActionPerformed

    private void enviarsaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarsaqueActionPerformed
        boolean teste;
        double valorSaque = Double.parseDouble(this.valorsaque.getText());
        teste = saque(valorSaque, this.nomeusuario2.getText());        
        if(teste == true){
            JOptionPane.showMessageDialog(null, "Valor insuficiente ou Conta não cadastrada");   
        }
        else{
            JOptionPane.showMessageDialog(null, "Saque realizado com sucesso");        
        }
    }//GEN-LAST:event_enviarsaqueActionPerformed

    private void enviarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarCadastroActionPerformed
        boolean teste = false;
        teste = cadastrarUser(this.nomeusuario3.getText(), this.senhausuario1.getText(), this.saldousuario.getText());
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
    }//GEN-LAST:event_enviarCadastroActionPerformed

    private void nomeusuarioantigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeusuarioantigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeusuarioantigoActionPerformed

    private void enviarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarAlteracaoActionPerformed
        boolean teste = false;
        teste = alterCadastro(this.nomeusuarioantigo.getText(), this.nomeusuarionovo.getText(), this.senhausuarioantigo.getText(), this.senhausuarionovo.getText());
        JOptionPane.showMessageDialog(null, "Alteracao realizada com sucesso");
    }//GEN-LAST:event_enviarAlteracaoActionPerformed

    private void consultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuarioActionPerformed
        String teste = "";
        teste = consultUser(this.nomeusuario4.getText(), this.senhausuario2.getText());
        JOptionPane.showMessageDialog(null, "Dados do usuario " + teste);
    }//GEN-LAST:event_consultarUsuarioActionPerformed

    private void nomeusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeusuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeusuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteHan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteHan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteHan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteHan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteHan().setVisible(true);
            }
            

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarUsuario;
    private javax.swing.JButton enviarAlteracao;
    private javax.swing.JButton enviarCadastro;
    private javax.swing.JButton enviardeposito;
    private javax.swing.JButton enviarsaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeusuario;
    private javax.swing.JTextField nomeusuario1;
    private javax.swing.JTextField nomeusuario2;
    private javax.swing.JTextField nomeusuario3;
    private javax.swing.JTextField nomeusuario4;
    private javax.swing.JTextField nomeusuarioantigo;
    private javax.swing.JTextField nomeusuarionovo;
    private javax.swing.JTextField saldousuario;
    private javax.swing.JTextField senhausuario;
    private javax.swing.JTextField senhausuario1;
    private javax.swing.JTextField senhausuario2;
    private javax.swing.JTextField senhausuarioantigo;
    private javax.swing.JTextField senhausuarionovo;
    private javax.swing.JTextField valordeposito;
    private javax.swing.JTextField valorsaque;
    private javax.swing.JButton verificarsaldo;
    // End of variables declaration//GEN-END:variables

    private static boolean alterCadastro(java.lang.String oldNome, java.lang.String newNome, java.lang.String oldSenha, java.lang.String newSenha) {
        ws.BankWS_Service service = new ws.BankWS_Service();
        ws.BankWS port = service.getBankWSPort();
        return port.alterCadastro(oldNome, newNome, oldSenha, newSenha);
    }

    private static boolean cadastrarUser(java.lang.String nome, java.lang.String senha, java.lang.String saldo) {
        ws.BankWS_Service service = new ws.BankWS_Service();
        ws.BankWS port = service.getBankWSPort();
        return port.cadastrarUser(nome, senha, saldo);
    }

    private static String consultUser(java.lang.String nome, java.lang.String senha) {
        ws.BankWS_Service service = new ws.BankWS_Service();
        ws.BankWS port = service.getBankWSPort();
        return port.consultUser(nome, senha);
    }

    private static boolean deposito(double valor, java.lang.String nome) {
        ws.BankWS_Service service = new ws.BankWS_Service();
        ws.BankWS port = service.getBankWSPort();
        return port.deposito(valor, nome);
    }

    private static double saldoUser(java.lang.String nome, java.lang.String senha) {
        ws.BankWS_Service service = new ws.BankWS_Service();
        ws.BankWS port = service.getBankWSPort();
        return port.saldoUser(nome, senha);
    }

    private static boolean saque(double valor, java.lang.String nome) {
        ws.BankWS_Service service = new ws.BankWS_Service();
        ws.BankWS port = service.getBankWSPort();
        return port.saque(valor, nome);
    }
}
